version: "2"
services:
  nginxTest:
    image: nginx
    container_name: nginxTest
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:80"
    restart: always
